# =================================
# ESG Config Service 설정
# 역할: 중앙집중식 설정 관리 (Git 기반)
# 포트: 8888
# =================================

server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: config-service

  # =================================
  # Spring Cloud Config Server 설정 (Git 방식)
  # =================================
  cloud:
    config:
      server:
        # Git 저장소에서 설정 읽기
        git:
          uri: ${GIT_URL}
          username: ${GIT_ID}
          password: ${GIT_TOKEN}
          clone-on-start: true
          timeout: 10
          refresh-rate: 60

        # 기본 설정
        default-application-name: application
        default-profile: default

# =================================
# Actuator 모니터링 설정
# =================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# =================================
# 콘솔 로깅 설정 (개발환경 최적화)
# =================================
logging:
  level:
    root: INFO
    "[com.nsmm.esg.config_service]": DEBUG
    "[org.hibernate.SQL]": ${LOG_SQL:false}
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"